module SBox
    (sbox) where

sbox :: [Bool] -> [Bool]
sbox [] = []
sbox m = s1 (take 8 m) ++ sbox (drop 8 m)

s1 :: [Bool] -> [Bool]
s1 (False : False : False : False : False : False : _)  = [True, True, True, False]
s1 (False : False : False : False : True : False : _)   = [False, True, False, False]
s1 (False : False : False : True : False : False : _)   = [True, True, False, True]
s1 (False : False : False : True : True : False : _)    = [False, False, False, True]
s1 (False : False : True : False : False : False : _)   = [False, False, True, False]
s1 (False : False : True : False : True : False : _)    = [True, True, True, True]
s1 (False : False : True : True : False : False : _)    = [True, False, True, True]
s1 (False : False : True : True : True : False : _)     = [True, False, False, False]
s1 (False : True : False : False : False : False : _)   = [False, False, True, True]
s1 (False : True : False : False : True : False : _)    = [True, False, True, False]
s1 (False : True : False : True : False : False : _)    = [False, True, True, False]
s1 (False : True : False : True : True : False : _)     = [True, True, False, False]
s1 (False : True : True : False : False : False : _)    = [False, True, False, True]
s1 (False : True : True : False : True : False : _)     = [True, False, False, True]
s1 (False : True : True : True : False : False : _)     = [False, False, False, False]
s1 (False : True : True : True : True : False : _)      = [False, True, True, True]

s1 (False : False : False : False : False : True : _)  = [False, False, False, False]
s1 (False : False : False : False : True : True : _)   = [True, True, True, True]
s1 (False : False : False : True : False : True : _)   = [False, True, True, True]
s1 (False : False : False : True : True : True : _)    = [False, True, False, False]
s1 (False : False : True : False : False : True : _)   = [True, True, True, False]
s1 (False : False : True : False : True : True : _)    = [False, False, True, False]
s1 (False : False : True : True : False : True : _)    = [True, True, False, True]
s1 (False : False : True : True : True : True : _)     = [False, False, False, True]
s1 (False : True : False : False : False : True : _)   = [True, False, True, False]
s1 (False : True : False : False : True : True : _)    = [False, True, True, False]
s1 (False : True : False : True : False : True : _)    = [True, True, False, False]
s1 (False : True : False : True : True : True : _)     = [True, False, False, False]
s1 (False : True : True : False : False : True : _)    = [True, False, False, True]
s1 (False : True : True : False : True : True : _)     = [False, True, False, True]
s1 (False : True : True : True : False : True : _)     = [False, False, True, True]
s1 (False : True : True : True : True : True : _)      = [True, False, False, False]

s1 (True : False : False : False : False : False : _)  = [False, True, False, False]
s1 (True : False : False : False : True : False : _)   = [False, False, False, True]
s1 (True : False : False : True : False : False : _)   = [True, True, True, False]
s1 (True : False : False : True : True : False : _)    = [True, False, False, False]
s1 (True : False : True : False : False : False : _)   = [True, True, False, True]
s1 (True : False : True : False : True : False : _)    = [False, True, True, False]
s1 (True : False : True : True : False : False : _)    = [False, False, True, False]
s1 (True : False : True : True : True : False : _)     = [True, False, True, True]
s1 (True : True : False : False : False : False : _)   = [True, True, True, True]
s1 (True : True : False : False : True : False : _)    = [True, True, False, False]
s1 (True : True : False : True : False : False : _)    = [True, False, False, True]
s1 (True : True : False : True : True : False : _)     = [False, True, True, True]
s1 (True : True : True : False : False : False : _)    = [False, False, True, True]
s1 (True : True : True : False : True : False : _)     = [True, False, True, False]
s1 (True : True : True : True : False : False : _)     = [False, True, False, True]
s1 (True : True : True : True : True : False : _)      = [False, False, False, False]

s1 (True : False : False : False : False : True : _)  = [True, True, True, True]
s1 (True : False : False : False : True : True : _)   = [True, True, False, False]
s1 (True : False : False : True : False : True : _)   = [True, False, False, False]
s1 (True : False : False : True : True : True : _)    = [False, False, True, False]
s1 (True : False : True : False : False : True : _)   = [False, True, False, False]
s1 (True : False : True : False : True : True : _)    = [True, False, False, True]
s1 (True : False : True : True : False : True : _)    = [False, False, False, True]
s1 (True : False : True : True : True : True : _)     = [False, True, True, True]
s1 (True : True : False : False : False : True : _)   = [True, False, True, True]
s1 (True : True : False : False : True : True : _)    = [False, False, True, True]
s1 (True : True : False : True : False : True : _)    = [False, False, True, True]
s1 (True : True : False : True : True : True : _)     = [True, True, True, False]
s1 (True : True : True : False : False : True : _)    = [True, False, True, False]
s1 (True : True : True : False : True : True : _)     = [False, False, False, False]
s1 (True : True : True : True : False : True : _)     = [False, True, True, False]
s1 (True : True : True : True : True : True : _)      = [True, True, False, True]

s1 _ = []
